version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: img-reducer-app
    ports:
      - "53798:3000"
    depends_on:
      - redis
    restart: always
    environment:
      - NODE_ENV=production

  redis:
    image: redis:latest
    container_name: img-reducer-redis
    ports:
      - "6379:6379"
