version: '3.8'

services:
  app:
    image: node:alpine3.19
    container_name: img-reducer-app
    working_dir: /app
    command: npm start
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: img-reducer-redis
    ports:
      - "6379:6379"

